### ISSUE TITLE
cset crashes if process with "idle" priority exists

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lpechacek/cpuset#20]
```
What steps will reproduce the problem?

1. Start a process with "idle" (SCHED_IDLE, see /usr/include/linux/sched.h) 
priority
2. Call e.g. "cset shield --unshield -v" to display the process

What is the expected output? What do you see instead?

Result is:
Traceback (most recent call last):
  File "/usr/bin/cset", line 47, in <module>
    main()
  File "/usr/lib/pymodules/python2.7/cpuset/main.py", line 228, in main
    command.func(parser, options, args)
  File "/usr/lib/pymodules/python2.7/cpuset/commands/shield.py", line 291, in func
    print_stats()
  File "/usr/lib/pymodules/python2.7/cpuset/commands/shield.py", line 315, in print_sys_stats
    proc.log_detailed_task_table(cset.unique_set(SYS_SET), '   ', 76)
  File "/usr/lib/pymodules/python2.7/cpuset/commands/proc.py", line 787, in log_detailed_task_table
    l.extend(task_detail_table(set.tasks, indent, width))
  File "/usr/lib/pymodules/python2.7/cpuset/commands/proc.py", line 776, in task_detail_table
    if width: l.append(istr + task_detail(task, width))
  File "/usr/lib/pymodules/python2.7/cpuset/commands/proc.py", line 730, in task_detail
    out2.append(policy[int(stat[statdef['rtpolicy']])])
IndexError: list index out of range

Problem is that policy[5] is not defined for idle priority, only policy[0] to 
policy[3] are defined. (Note that SCHED_ISO is reserved, so policy[4] has to be 
reserved, too.)

What version of the product are you using? On what operating system?

cset 1.5.6
Linux 3.13.0-49, Ubuntu 14.04, x86_64

```

Original issue reported on code.google.com by `boris1...@nurfuerspam.de` on 30 Apr 2015 at 9:46

**Comment by lpechacek** [comment]
Fixed with commit de1ae0d598c2.  Thanks for the report!
