### ISSUE TITLE
Doesn't work after building with setup.py: No module named 'future'

### ISSUE THREAD

**Issue by HunterGraubard** [lpechacek/cpuset#31]
I followed the instructions in the INSTALL file, and ran `python setup.py install`.
Now when I try to run the compiled binary with `cset`, it fails:

> Traceback (most recent call last):
>   File "/usr/bin/cset", line 44, in <module>
>     from cpuset.main import main
>   File "/usr/lib/python3.7/site-packages/cpuset/main.py", line 7, in <module>
>     from future import standard_library
> ModuleNotFoundError: No module named 'future'

It seems that there's some undocumented dependency?

**Comment by MawKKe** [comment]
Related: on Ubuntu 20.04, installing the `cpuset` package via apt results in the same error. It can be fixex by installing the `python3-future` package

**Comment by yanivx** [comment]
Hi Team,

I am having a gitenv.sh where we import modules I am importing the module with below code 

`python -m pip install --index-url=$PYPI_URL future=0.18.2` 

What is the name of the package i should be using it is not able to find a package with name python-future
